RegisterNetEvent('showWelcomeScreen')
AddEventHandler('showWelcomeScreen', function()
    local welcomeScreen = CreateWebUI('file://' .. GetResourcePath(GetCurrentResourceName()) .. '/welcome.html', 0, 0, 0, true)
    SetWebVisibility(welcomeScreen, WEB_VISIBLE)
    SetWebAnchors(welcomeScreen, 0, 0, 1, 1)
    Citizen.Wait(10000)
    SetWebVisibility(welcomeScreen, WEB_HIDDEN)
    DestroyWebUI(welcomeScreen)
end)
